// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcs_rcpp_read_data
NumericMatrix fcs_rcpp_read_data(const std::string& file_path, long byte_offset, long n_row, long n_par, bool swap);
RcppExport SEXP _flowstate_fcs_rcpp_read_data(SEXP file_pathSEXP, SEXP byte_offsetSEXP, SEXP n_rowSEXP, SEXP n_parSEXP, SEXP swapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< long >::type byte_offset(byte_offsetSEXP);
    Rcpp::traits::input_parameter< long >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< long >::type n_par(n_parSEXP);
    Rcpp::traits::input_parameter< bool >::type swap(swapSEXP);
    rcpp_result_gen = Rcpp::wrap(fcs_rcpp_read_data(file_path, byte_offset, n_row, n_par, swap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flowstate_fcs_rcpp_read_data", (DL_FUNC) &_flowstate_fcs_rcpp_read_data, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_flowstate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
