# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcs_rcpp_read_data <- function(file_path, byte_offset, n_row, n_par, swap) {
    .Call(`_flowstate_fcs_rcpp_read_data`, file_path, byte_offset, n_row, n_par, swap)
}

