## convert non-numeric (factored; logical) [['data']] columns
## update [['parameters']]
## needs reassignment
data.parameters.update <- function(flowstate){
  ##
  data.cols.to.numeric <- flowstate[['data']][
    ,
    j = {
      res <- sapply(.SD, class)
      res[res != "numeric"]
    },
    .SDcols = !'sample.id'
  ]
  ##
  for(j in names(data.cols.to.numeric)){
    data.table::set(
      x = flowstate[['data']],
      j = j,
      value = as.numeric(flowstate[['data']][[j]])
    )
  }
  ##
  flowstate$parameters <- rbind(
    flowstate$parameters,
    data.table::data.table(
      par = paste0(
        '$P',
        (seq(length(data.cols.to.numeric)) + flowstate$parameters[, .N])
      ),
      B = "32",
      DISPLAY = "LIN",
      E = "0,0",
      N = names(data.cols.to.numeric),
      R = flowstate$data[
        ,
        j = sapply(.SD, function(j){as.character(max(ceiling(as.numeric(j))))}),
        .SDcols = names(data.cols.to.numeric)
      ],
      TYPE = sprintf("Derived_%s", tools::toTitleCase(data.cols.to.numeric))
    ),
    fill = TRUE
  )
  ##
  invisible(flowstate)
}

## convert non-character (factored) [['keywords']] columns
## update [['keywords']]
keywords.to.character <- function(flowstate){
  keywords.cols.to.character <- flowstate[['keywords']][
    ,
    j = {
      res <- sapply(.SD, class)
      res[res != "character"]
    },
    .SDcols = !'sample.id'
  ]
  ## convert to character in [['keywords']]
  for(j in names(keywords.cols.to.character)){
    if(keywords.cols.to.character[[j]] == "factor"){
      .value <- sprintf(
        "FACTOR::%s",
        paste0(flowstate$keywords[[j]], collapse = ";")
      )
      ##
      data.table::set(
        x = flowstate[['keywords']],
        j = j,
        value = .value
      )
      flowstate[['keywords']][, (j) := as.character(.SD[[j]])]
    }
  }
}

## checks with some verbose output;
## eventually update with automatic execution of the individually named functions within the check
write.flowstate.check <- function(flowstate,verbose=TRUE){
  ##
  res <- attr(flowstate$spill,'applied')
  if(res){
    if(verbose){
      message("Decompensate using flowstate::spillover.apply(...,decompensate = TRUE)")
      print(res)
    }
  }
}

## [['parameters']] (data.table) to vector (string); helper function
parameters.to.string <- function(flowstate){
  cols.parameters <- names(flowstate[['parameters']])[
    names(flowstate[['parameters']]) %in% flowstate.parameter.keywords
  ]
  parms <- lapply(cols.parameters, function(
    p,
    par.n = flowstate[['parameters']][, .N])
  {
    vec <- stats::setNames(
      as.character(flowstate[['parameters']][[p]]),
      nm = paste0(ifelse(p == 'DETECTOR|DISPLAY', "P", "$P"), seq(par.n), p)
    )
    return(vec)
  })
  parms <- unlist(parms)
  parms <- parms[order(names(parms))]
  parms <- parms[!is.na(parms)]
  ##
  return(parms)
}

## [['spill']] (data.table) to vector (string); helper function
spill.to.string <- function(flowstate){
  spill <- data.table::copy(flowstate[['spill']])
  col.match <- match(names(flowstate[['spill']]), names(flowstate[['data']]))
  data.table::setnames(spill, new = flowstate[['parameters']][['N']][col.match])
  ##
  spill.string <- paste0(
    c(
      spill[, .N],
      paste0(names(spill), collapse = ","),
      paste0(c(t(as.matrix(spill))), collapse = ",")
    ),
    collapse = ","
  )
  names(spill.string) <- '$SPILLOVER'
  ##
  return(spill.string)
}

#' @title Write a `flowstate` as a Flow Cytometry Standard file (FCS 3.1)
#' @description
#' A `flowstate` -- following [Flow Cytometry Standard](https://pmc.ncbi.nlm.nih.gov/articles/PMC2892967/) conventions -- is converted to FCS 3.1 and written to disk. The conversion is as follows:
#' * `[['keywords']]`, `[['parameters']]`, and `[['spill']]` (if present) are converted to character string using a delimiter `"|"` to separate keyword-value pairs.
#'   * this string forms the `TEXT` segment of the FCS file.
#' * `[['data']]` is written as row-major binary.
#'   * this forms the `DATA` segment of the FCS file.
#' * The `HEADER` segment (string) -- containing the required offsets -- is derived from `TEXT` and `DATA`.
#'
#' The FCS 3.1 compliant file is then written to disk.
#'
#' *N.B.: During testing, FCS 3.1 files written to disk by [write.flowstate] were fully compatible with [read.flowstate] and [flowCore::read.FCS]; issues were only with proprietary software (i.e., FlowJo). If proprietary software is to be used with FCS 3.1 files generated by [write.flowstate], caution is advised.*
#'
#' @param flowstate A `flowstate` as returned from [read.flowstate].
#' @param file.dir A [file.path] -- default [tempdir]; a file directory for saving the output FCS 3.1 file(s).
#' @param endianness Character string -- default `"little"`; see [endian][base::writeBin].
#'
#' @returns
#' \itemize{
#'    \item FCS 3.1 file(s) are written to disk and a summary message is displayed.
#'    \item UPDATES BY REFERENCE:
#'       \itemize{
#'          \item `flowstate[['data']]` -- non-numeric (logical and/or factor) columns are converted to numeric
#'          \item `flowstate[['keywords']]` -- non-character (factor) columns are converted to character
#'          \item `flowstate[['spill']]` -- column names are matched/updated using `[['parameters']][['N']]`
#'       }
#'    \item UPDATES BY ASSIGNMENT to environment:
#'      \itemize{
#'         \item `flowstate[['parameters']]` -- `[['parameters']]` is updated by row-binding derived columns found in `[['data']]`
#'      }
#' }
#'
#' Invisibly returns `flowstate`.
#' @export
#'
#' @examples
#'
#' fcs.file.paths <- system.file("extdata", package = "flowstate") |>
#' list.files(full.names = TRUE, pattern = "BLOCK.*.fcs")
#'
#' ## read .fcs files as a flowstate object; concatenate
#' fs <- read.flowstate(
#'   fcs.file.paths,
#'   colnames.type = "S",
#'   concatenate = TRUE
#' )
#'
#' ## saturating events -- logical
#' select_nonsaturating(fs)
#'
#' ## singlet events -- logical
#' select_singlets(fs)
#'
#' ## transform
#' flowstate.transform(fs)
#'
#' ## simple logical to select CD3+
#' fs$data[
#' ,
#' j = select.CD3 := {
#'  d <- stats::density(CD3[(select.nonsaturating) & (select.singlets)])
#'  pv <- diff(sign(diff(d$y)))
#'  valley <- which(pv == 2) + 1
#'  CD3 > d$x[valley]
#'  }
#' ]
#'
#' ## add a factor -- 'aliquot'
#' fs$keywords[
#'  ,
#'  j = aliquot := data.table::tstrsplit(sample.id, "_", keep = 5, type.convert = factor)
#' ]
#'
#' add.keywords.to.data(fs, 'aliquot')
#'
#' ## write; reassign to capture the updated flowstate
#' fs <- write.flowstate(fs)
#'
#' ## read newly written files
#' fcs.file.paths <- list.files(tempdir(), full.names = TRUE, pattern = "flowstateMOD.fcs")
#'
#' fs <- read.flowstate(
#'   fcs.file.paths,
#'   colnames.type = "S",
#'   concatenate = TRUE
#' )
#'
#' ## derived [['data']] columns
#' fs[['data']][, .(select.nonsaturating, select.singlets, select.CD3, aliquot)]
#'
#' ## derived [['parameters']] columns
#' fs$parameters[grep("Logical|Factor", TYPE)]
#'
#' ## derived [['keyword']] columns -- retains original factor levels
#' fs[['keywords']][, .(aliquot)]
#' ## recover the factor levels -- optional
#' levels.aliquot <- unique(fs[['keywords']][, sub('FACTOR::', "", aliquot)])
#' levels.aliquot <- strsplit(levels.aliquot, ';')[[1]]
#' fs$keywords[, aliquot := factor(levels.aliquot)]
#' fs$data[, aliquot := NULL]
#' add.keywords.to.data(fs, 'aliquot')
#'
#' ## plot derived [['data']] logicals (now numeric)
#' plot(fs, FSC_A, FSC_H) + ggplot2::facet_wrap(~select.singlets)
#' flowstate.transform(fs)
#' plot(fs, CD3) + ggplot2::facet_wrap(~select.CD3)
#'
write.flowstate <- function(
    flowstate,
    file.dir = tempdir(),
    endianness = c('little', 'big')
)
{
  ## PREPARE flowstate -- START
  ## inverse transformation of [['data']] columns
  suppressMessages(
    flowstate.transform.inverse(flowstate)
  )

  ## convert non-numeric (factored; logical) [['data']] columns
  ## update [['parameters']] to match [['data']]; derived columns
  flowstate <- data.parameters.update(flowstate)

  ## convert non-character (factored/numeric) [['keyword']] columns
  keywords.to.character(flowstate)
  ## PREPARE flowstate -- END

  ##
  byteord <- switch(
    match.arg(endianness),
    little = "1,2,3,4",
    big = "4,3,2,1"
  )

  ## required FCS keywords
  keywords.required <- fcs.text.primary.required.keywords.zero
  keywords.required[['$BYTEORD']] <- byteord
  keywords.required[['$DATATYPE']] <- 'F'
  keywords.required[['$MODE']] <- "L"

  ## split and write
  lapply(split(flowstate, f = 'sample.id'), function(.flowstate){
    ## NULL out the identifier -- 'sample.id'
    .flowstate[['data']][, sample.id := NULL]
    .flowstate[['keywords']][, sample.id := NULL]
    ## vector (string) of keywords
    keyword.string <- c(
      keywords.required,
      parameters.to.string(.flowstate),
      unlist(.flowstate[['keywords']])
    )
    if('spill' %in% names(.flowstate)){
      keyword.string <- c(
        keyword.string,
        spill.to.string(.flowstate)
      )
    }
    ## vector (string) of keywords to list
    keyword.list <- as.list(keyword.string)
    keyword.list <- keyword.list[order(names(keyword.list))]
    ## update; flowstate-specific
    keyword.list[['$TOT']] <- as.character(.flowstate$data[,.N])
    ##
    N.parameters <- .flowstate[['parameters']][, .N]
    N.data <- ncol(.flowstate[['data']])
    res <- N.parameters == N.data
    stopifnot("[['parameters']] / [['data']] conflict: $PAR not equal" = res)
    keyword.list[['$PAR']] <- as.character(N.parameters)
    ## update '$FIL'
    fil <- sub(".fcs", "", keyword.list[['$FIL']], ignore.case = T)
    fil <- sprintf("%s_flowstateMOD.fcs", fil)
    keyword.list[['$FIL']] <- fil
    # if(!is.null(new.fil)){
    #   if(add.fil.mod){
    #     new.fil <- sprintf("%s_flowstateMOD", new.fil)
    #   }
    #   if(!grepl(".fcs$", new.fil)){
    #     new.fil <- paste0(new.fil, ".fcs")
    #   }
    #   keyword.list[['$FIL']] <- new.fil
    # }

    ## TEXT segment
    text.segment <- paste0(
      "|",
      paste0(names(keyword.list), "|", keyword.list, "|", collapse = "")
    )
    TEXT.start <- 58
    TEXT.end <- nchar(text.segment, "bytes") + TEXT.start - 1

    data.stream.bytes <- (
      .flowstate[['data']][,.N] *
        ncol(.flowstate[['data']]) * 4
    )
    ## from flowCore::write.FCS()
    ## in 'text.segment': $BEGINDATA = "0" and $ENDDATA = "0"
    ## combined, nchar = 2
    kw.len.old <- 2
    repeat {
      DATA.start <- TEXT.end + 1
      DATA.end <- DATA.start + data.stream.bytes - 1
      kw.len.new <- nchar(DATA.start) + nchar(DATA.end)
      if (kw.len.new > kw.len.old) {
        TEXT.end <- TEXT.end + kw.len.new - kw.len.old
        kw.len.old <- kw.len.new
      }
      else break
    }
    ## update 'text.segment'
    regmatches(
      x = text.segment,
      m = gregexpr("BEGINDATA|0",text.segment, fixed = TRUE)
    ) <- paste("BEGINDATA", DATA.start, sep = "|")
    regmatches(
      x = text.segment,
      m = gregexpr("ENDDATA|0", text.segment, fixed = TRUE)
    ) <- paste("ENDDATA", DATA.end, sep = "|")
    ## test
    if(nchar(text.segment, "bytes") + TEXT.start - 1 != DATA.start - 1){
      stop("Issue with updating 'text.segment' with '$BEGINDATA' and/or '$ENDDATA' values.")
    }
    ## initialize a list for storing byte offsets
    offsets <- stats::setNames(
      vector(mode = "list", length = 3L),
      nm = c("TEXT", "DATA", "ANALYSIS")
    )
    offsets$TEXT <- c(TEXT.start, TEXT.end)
    offsets$DATA <- c(DATA.start, DATA.end)
    offsets$ANALYSIS <- c(0, 0)
    ## prepare the HEADER segment
    header.segment <- paste0(
      sapply(offsets, function(i){
        if(any(nchar(i) > 8)){
          i <- c(0, 0)
        }
        paste0(sprintf("%8s", i), collapse = "")
      }),
      collapse = ""
    )
    version <- sprintf("%-10s", "FCS3.1")
    header.segment <- paste0(version, header.segment)
    if(nchar(header.segment) != 58){
      stop("HEADER segment does not match expected byte length/nchar of 58")
    }
    ##
    if(!dir.exists(file.dir)) {
      dir.create(file.dir, recursive = T)
    }
    ##
    filename <- file.path(file.dir, keyword.list[['$FIL']])
    con <- file(filename, open = "wb")
    on.exit(close(con))
    seek(con, 0)
    writeChar(header.segment, con, eos = NULL)
    writeChar(text.segment, con, eos = NULL)
    ##
    data.segment <- methods::as(t(.flowstate$data), "numeric")
    writeBin(
      object = data.segment,
      con,
      size = 4,
      endian = 'little'#match.arg(endianness)
    )
    writeChar("00000000", con, eos = NULL)
    ##
    obj <- deparse(substitute(flowstate))
    message(sprintf("%s --> %s", obj, filename))
  }) |> invisible()
  ##
  invisible(flowstate)
}
